version: "1"
rules:
  - base: main
    upstream: goauthentik/authentik
    mergeMethod: hardreset
  - base: komodo-deploy
    upstream: main
    mergeMethod: rebase
    assignees:
      - b-
    reviewers:
      - b-
    conflictReviewers:
      - b-
label: ":arrow_heading_down: pull" # Optional
conflictLabel: "merge-conflict" # Optional, on merge conflict assign a custom label, Default: merge-conflict

