---
version: "3.4"

services:
  postgresql:
    env_file: stack.env
  server:
    env_file: stack.env
    volumes:
      - ./media/custom-css.css:/web/dist/custom.css
    depends_on:
      media-deploy:
          condition: service_completed_successfully
          # commented out because harbormaster gets mad
          # required: false # warns us if not satisfied, but won't prevent service start
  worker:
    env_file: stack.env
    depends_on:
      media-deploy:
          condition: service_completed_successfully
          # required: false # warns us if not satisfied, but won't prevent service start

  media-deploy: # Deploys the `media` volume
    image: ghcr.io/perchnet/authentik-win95-setup:main
    volumes:
      - ./media:/media
      - ./custom-templates:/templates