---
version: "3.4"

networks:
  default:
  external:
    name: traefik
    external: true

services:
  postgresql:
    env_file: stack.env
  server:
    env_file: stack.env
    networks:
      - default
      - external
    labels:
      - traefik.enable=true
      - "traefik.http.routers.authentik.rule=${TRAEFIK_RULE_PREFIX}auth${TRAEFIK_RULE_SUFFIX}"
  worker:
    env_file: stack.env
    networks:
      - default
      - external
  authentik-proxy:
    container_name: authentik-proxy.internal
    networks:
      - default
      - external
    ports:
      - 9000:9000
      - 9443:9443
    image: ghcr.io/goauthentik/proxy:${AUTHENTIK_TAG:-2025.4.1}
    restart: unless-stopped
    environment:
      AUTHENTIK_HOST: http://server:9000
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: ${AUTHENTIK_TOKEN:?AUTHENTIK_TOKEN is not set}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik-proxy.rule=PathPrefix(`/outpost.goauthentik.io/`)"
      - traefik.http.middlewares.authentik-auth.forwardauth.address=http://authentik-proxy.internal:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik-auth.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authentik-auth.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

      #- "traefik.http.routers.authentik-proxy.entrypoints=websecure"
