[[stack]]
name = "socket-proxy"
tags = ["authentik"]
[stack.config]
server = "komodo"
poll_for_updates = true
destroy_before_deploy = true
linked_repo = "authentik-deploy"
run_directory = "socket-proxy"
file_paths = [
  "compose.yaml"
]
environment = """
TS_AUTHKEY=[[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]?ephemeral=true
"""

[[stack]]
name = "authentik"
tags = ["authentik"]
[stack.config]
server = "auth"
links = [
  "https://github.com/b-/authentik-deploy",
  "https://auth.shark-perch.ts.net",
  "https://auth.ibeep.com"
]
project_name = "authentik_live"
poll_for_updates = true
destroy_before_deploy = true
linked_repo = "authentik-deploy"
file_paths = [
  "docker-compose.yml",
  "docker-compose.override.yaml",
  "backup.yaml"
]
env_file_path = ".env"
environment = """
PG_USER=authentik
PG_PASS=[[OP__KOMODO__AUTHENTIK__PG_PASS]]
AUTHENTIK_SECRET_KEY=[[OP__KOMODO__AUTHENTIK__AUTHENTIK_SECRET_KEY]]
AUTHENTIK_EMAIL__HOST=smtp.sendgrid.net
AUTHENTIK_EMAIL__PORT=465
AUTHENTIK_EMAIL__USERNAME=[[OP__KOMODO__SENDGRID_SMTP_API__USERNAME]]
AUTHENTIK_EMAIL__PASSWORD=[[OP__KOMODO__SENDGRID_SMTP_API__CREDENTIAL]]
AUTHENTIK_EMAIL__USE_TLS=false
AUTHENTIK_EMAIL__USE_SSL=true
AUTHENTIK_EMAIL__TIMEOUT=10
AUTHENTIK_EMAIL__FROM=[[OP__KOMODO__SENDGRID_SMTP_API__FROM]]
AUTHENTIK_TOKEN=[[OP__KOMODO__AUTHENTIK__PROXY_TOKEN]]
COMPOSE_PORT_HTTP=81
COMPOSE_PORT_HTTPS=443
BACKUP_ON_START=TRUE
POSTGRES_DB=postgres
TRAEFIK_RULE_PREFIX=[[OP__KOMODO__TRAEFIK__RULE_PREFIX]]
TRAEFIK_RULE_SUFFIX=[[OP__KOMODO__TRAEFIK__RULE_SUFFIX]]
TS_AUTHKEY=[[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]?ephemeral=true
TSIDP_AUTHKEY=[[TSIDP_KEY]]
"""

##

[[repo]]
name = "authentik-deploy"
tags = ["authentik"]
[repo.config]
server = "auth"
builder = "auth"
git_account = "b-"
repo = "b-/authentik-deploy"
branch = "komodo"

##

[[procedure]]
name = "deploy-authentik"
tags = ["authentik"]

[[procedure.config.stage]]
name = "update repo"
enabled = true
executions = [
  { execution.type = "CloneRepo", execution.params.repo = "authentik-deploy", enabled = true },
  { execution.type = "RunSync", execution.params.sync = "authentik-sync", enabled = true },
  { execution.type = "DeployStackIfChanged", execution.params.stack = "authentik", enabled = true }
]
