secrets:
  ts_authkey:
    environment: "TS_AUTHKEY"
  tsidp_authkey:
    environment: "TSIDP_AUTHKEY"
configs:
  acme-redirect.conf:
    content: |
      [acme]
      acme_email = "certs@ibeep.com"
      #acme_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
      renew_if_days_left = 30
  acme-redirect-domain.conf:
    content: |
      [cert]
      name = "auth.ibeep.com"
      dns_names = [
        "auth.ibeep.com",
        "auth-01.ibeep.com",
      ]
      exec = [
        "mkdir -p /srv/authentik/certs/auth.ibeep.com",
        "cp -fv /srv/acme-redirect/data/live/auth.ibeep.com/fullchain /srv/authentik/certs/auth.ibeep.com/fullchain.pem",
        "cp -fv /srv/acme-redirect/data/live/auth.ibeep.com/privkey /srv/authentik/certs/auth.ibeep.com/privkey.pem",
      ]
  server_serve:
    content: |
      {
          "TCP": {
              "443": {
                  "HTTPS": true
              }
          },
          "Web": {
              "$${TS_CERT_DOMAIN}:443": {
                  "Handlers": {
                      "/": {
                          "Proxy": "https+insecure://localhost:9443"
                      }
                  }
              }
          },
          "AllowFunnel": {
              "$${TS_CERT_DOMAIN}:443": true
          }
      }
x-service_templates:
  x-ts-sidecar: &ts-sidecar
    image: tailscale/tailscale:latest
    secrets:
      - ts_authkey
    environment: &ts-env
      TS_AUTHKEY: "file:/run/secrets/ts_authkey"
      TS_EXTRA_ARGS: "--advertise-tags=tag:docker"
      TS_ENABLE_HEALTH_CHECK: true
      TS_LOCAL_ADDR_PORT: 127.0.0.1:41234
      TS_STATE: "mem:"
    #   TS_USERSPACE: false
    # devices:
    #   - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    # cap_add:
    #   - net_admin # Tailscale requirement
    #   - sys_module # Tailscale requirement
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: always

services:
  postgresql:
    env_file: stack.env
  server-ts:
    <<: *ts-sidecar
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    environment:
      <<: *ts-env
      TS_HOSTNAME: "auth"
      TS_SERVE_CONFIG: /config/ts_serve.json
    configs:
      - source: server_serve
        target: /config/ts_serve.json
    labels:
      - traefik.enable=true
      - "traefik.http.routers.authentik.rule=${TRAEFIK_RULE_PREFIX}auth${TRAEFIK_RULE_SUFFIX}"
      - "traefik.http.services.authentik.loadbalancer.server.port=${COMPOSE_PORT_HTTP:-9000}:9000"
  server:
    env_file: stack.env
    network_mode: service:server-ts
    ports: !reset []
    volumes: !override
      - /srv/authentik/media:/media
      - /srv/authentik/custom-templates:/templates
      - /srv/authentik/custom-templates/custom-css.css:/web/dist/custom.css
  worker:
    volumes: !override
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/authentik/certs:/certs
      - /srv/authentik/media:/media
      - /srv/authentik/custom-templates:/templates
      - /srv/authentik/custom-templates/custom-css.css:/web/dist/custom.css
    env_file: stack.env

  tsidp:
    container_name: tsidp
    #ports:
    #    - 443:443
    environment:
      TS_AUTHKEY: "${TSIDP_AUTHKEY}"
      TS_STATE_DIR: /var/lib/tsidp
      TAILSCALE_USE_WIP_CODE: "1"
    volumes:
      - /srv/tsidp/data:/var/lib/tsidp
    image: ghcr.io/tailscale/tsidp:latest
    command: tsidp-server --funnel --enable-debug --verbose --hostname=tsidp

  acme-redirect:
    #image: ghcr.io/kpcyrd/acme-redirect:latest
    build: https://github.com/kpcyrd/acme-redirect.git#main
    command: daemon -vvv
    environment:
      ACME_DATA_DIR: /srv/acme-redirect/data
    volumes:
      - /srv/authentik/certs:/srv/authentik/certs
      - /srv/acme-redirect/data:/srv/acme-redirect/data
      - /srv/acme-redirect/challs:/run/acme-redirect/challs
    ports:
      - 80:80
    configs:
      - source: acme-redirect.conf
        target: /etc/acme-redirect.conf
      - source: acme-redirect-domain.conf
        target: /etc/acme-redirect.d/auth.ibeep.com.conf
