# This is a basic workflow to help you get started with Actions

name: Check for update

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 */4 * * *' # every 4th hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
      compose: ${{ steps.diff.outputs.compose }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compare to upstream docker-compose.yml
        id: diff
        run: |
          if ! curl -sLo- https://goauthentik.io/docker-compose.yml \
              | diff docker-compose.yml - ; then
            echo 'changed=true' | tee -a "$GITHUB_OUTPUT"
            echo 'compose<<EOF' | tee -a $GITHUB_OUTPUT
            cat docker-compose.yml | tee -a $GITHUB_OUTPUT
            echo 'EOF' | tee -a $GITHUB_OUTPUT
          fi

  # Run the job only with "compose_changed" equals "true"
  branch-and-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: diff
    if: needs.diff.outputs.changed == 'true'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set environments
        run: echo "NEW_BRANCH=update-docker-compose-yml-$(date +%Y-%m-%d_%H%M%S-utc)" >> $GITHUB_ENV
      - name: Configure git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Update docker-compose.yml
        run: |
          curl -sLo docker-compose.yml https://goauthentik.io/docker-compose.yml
          git add docker-compose.yml
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Update docker-compose.yml
            title: Update docker-compose.yml
            body: |
              
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: ${{ env.NEW_BRANCH }}
