name: Check for update
env:
  URL: "https://raw.githubusercontent.com/goauthentik/authentik/master/docker-compose.yml"
  FILE: "docker-compose.yml"
on:
  push:
  schedule:
    - cron: '0 */4 * * *' # every 4th hour
  workflow_dispatch:
jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: current_version
        run: echo "CURRENT_VERSION=$(grep -m1 -Poe '([[:digit:]]{4}\.[[:digit:]]{1,2}\.[[:digit:]]{1,2})' docker-compose.yml)" | tee -a $GITHUB_OUTPUT
      - name: Download ${{ env.FILE }}
        run: curl -sLo "${FILE}" "${URL}"
      - name: Get new version
        id: new_version
        run: echo "NEW_VERSION=$(grep -m1 -Poe '([[:digit:]]{4}\.[[:digit:]]{1,2}\.[[:digit:]]{1,2})' docker-compose.yml)" | tee -a $GITHUB_OUTPUT
      - name: Create Pull Request
        if: ${{ steps.new_version.outputs.NEW_VERSION != steps.current_version.outputs.CURRENT_VERSION }}
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: 'docker-compose.yml: Update to ${{ steps.new_version.outputs.NEW_VERSION }}'

            title: Update ${{ env.FILE }}
            body: |
              Auto-generated by [create-pull-request][1]

              Old version: ${{ steps.current_version.outputs.CURRENT_VERSION }}
              New version: ${{ steps.new_version.outputs.NEW_VERSION }}

              [1]: https://github.com/peter-evans/create-pull-request
            branch: update
